name: super_editor
description: Configurable, composeable, extensible text editor and document renderer for Flutter.
version: 0.1.6
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0
  http: ^0.13.1
  linkify: ^4.0.0
  # TODO: move markdown serialization to a separate package and
  #       then remove this dependency.
  markdown: ^4.0.0
  flutter_lints: ^1.0.0
  uuid: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.4

flutter:
  # no Flutter configuration
